Django6/src/Blog/urls.py
'''
Created on 2018. 6. 30.

@author: KGITBank
'''
from django.urls import path
from .views import *
app_name='Blog'
urlpatterns=[
    #클래스뷰.as_view() : 클래스 뷰가 URL매칭시 사용
    path('', index.as_view(), name='index'),
    path('<int:post_id>/', detail, name='detail'),
    path('posting/', posting, name='posting')
    path('serach/', searchP, name='serachP')
    ]







Django6/src/Django6/urls.py
from django.contrib import admin
from django.urls import path, include
#해당 파일이 view 함수를 알아야되므로 from ~ import로 함수 추가
#urls.py와 views.py가 다른 파일 위치이므로 절대경로로 표현
from vote.views import * #vote폴더 안에 views파일 중 index함수 추가
urlpatterns = [
    path('admin/', admin.site.urls),
    #path(문자열, 함수명) : 웹 클라이언트가 문자열에 해당하는 URL로
    #접근 시 매칭된 함수를 호출함  
    #http://127.0.0.1:8000 주소로 접근시
    #vote 어플리케이션 내의 index 함수 호출
    #http://127.0.0.1:8000/vote/ 로 시작하는 URL들을
    #vote폴더 안에있는 urls 파이썬파일로 처리하도록 매칭
    path('vote/', include('vote.urls')),
    #include하면서 그룹이름을 정하고싶은 경우
    #path('vote/',include('vote.urls', namespace='vote') )
    path('login/', include('customlogin.urls') ),
    path('auth/', include('social_django.urls', namespace='social')  ),
    path('blog/',include('Blog.urls'))
]
from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)












Django6/src/customlogin/urls.py
'''
Created on 2018. 6. 24.

@author: KGITBank
'''
from django.urls.conf import path
from .views import *
#인증(로그인,로그아웃, 회원가입)에 관한 뷰가 있는 파일
from django.contrib.auth import views 
app_name = 'customlogin'
urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', signin, name='signin'),
    path('logout/',views.logout, name='logout')
    ]










Django6/src/Blog/models.py
from django.db import models
#글 종류 : PostType
class PostType(models.Model):
    name = models.CharField('구분', max_length=50)
    def __str__(self):
        return self.name
#글 : Post
from django.conf import settings
class Post(models.Model):
    type = models.ForeignKey(PostType,on_delete=models.CASCADE)
    headline = models.CharField('제목',max_length=200)
    #blank : 사용자가 입력양식으로 입력할때 빈칸으로 둬도 되도록 허용
    #null : 데이터베이스에 저장할때 빈칸으로 둬도 되도록 허용
    content = models.TextField('내용', blank=True, null=True)
    #auto_now_add : 웹서버 기준의 현재시간으로 자동 입력됨
    pub_date = models.DateField('날짜', auto_now_add=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
#이미지, 파일을 저장, 관리하기 위해서 Django에서 'Pillow' 라이브러리를 사용 
#글에 포함된 이미지 : Image
class Image(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    #upload_to 변수 안에 %Y : 현재 년도, %m : 현재 월, %d : 현재 일을 문자열에
    #넣어 객체가 생성된 시점에 따라 자동으로 분류해줌 
    image = models.ImageField('이미지파일', upload_to='images/%Y/%m/%d')
    #ImageField는 이미지가 저장된 경로를 가지고있어, 객체가 제거되도 실제 이미지
    #파일은 제거되지 않음. 때문에 delete함수를 오버라이딩해 해당경로에 저장된
    #이미지를 지우는 행동이 필요함
    def delete(self, using=None, keep_parents=False):
        self.image.delete() #객체가 가지고있는 이미지경로에 있는 파일을 삭제
        return models.Model.delete(self, using=using, keep_parents=keep_parents)
#글에 포함된 파일 : File
class File(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    file = models.FileField('파일', upload_to="files/%Y/%m/%d")
    def delete(self, using=None, keep_parents=False):
        self.file.delete()
        return models.Model.delete(self, using=using, keep_parents=keep_parents)















Django6/src/Blog/forms.py
'''
Created on 2018. 6. 30.

@author: KGITBank
'''
from django.forms.models import ModelForm
from .models import Post,Image,File

class PostForm(ModelForm):
    class Meta:
        model = Post
        exclude = ('pub_date','author')
        
    def __init__(self, *args, **kwargs): 
        super(PostForm,self).__init__(*args,**kwargs)
        #사용자가 글종류를 선택하지 않았을 때의 기본값
        self.fields['type'].empty_label = None












Django6/src/Blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.list import ListView
from .models import *
from Blog.forms import *
from django.http.response import HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth.models import User


#재네릭뷰 : 장고에서 제공하는 여러가지 기능으로 나눈 뷰 클래스
#클래스 기반의 뷰
#class 뷰이름(기능별 뷰클래스):
#ListView : 특정 객체의 목록을 다루는 기능을 가진 뷰 클래스

class index(ListView):
    template_name = "Blog/templates/index.html"
    model = Post
    context_object_name = 'list'
    paginate_by = 5
    #template_name='' html파일 문자열을 넣음
    #model : 모델클래스명을 입력
    #context_object_name : 탬플릿에서 사용할 객체 리스트의 변수명
    #paginate_by : 한페이지에 몇개의 객체가 보일지 숫자를 입력

def detail(request, post_id):
    obj = get_object_or_404(Post,pk=post_id)
    return render(request, 'blog/templates/detail.html',{'post' : obj})

from django.contrib.auth.decorators import login_required
#from .forms import *  상단에 작성
@login_required
def posting(request):
    if request.method == "GET":
        form = PostForm()
        return render(request, "blog/templates/posting.html",{"form":form})
    elif request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            #글쓴이를 저장하는 변수가 빈공간이므로 바로 데이터베이스에 저장하지
            #않고 Post객체로 변환
            obj = form.save(commit=False)
            obj.author = request.user #요청한 클라이언트의 유저와 매칭 
            obj.save()                #객체를 데이터베이스에 저장
            #request.FILES : 클라이언트가 보낸 파일들에 대한 데이터
            #Image 객체 생성 및 저장
            #HTML 폼에서 name이 images로 지정된 파일을 추출
            for f in request.FILES.getlist('images'):
                image = Image(post=obj, image=f)#Image객체 생성
                image.save()                    #DB에 저장
            #File 객체 생성 및 저장
            for f in request.FILES.getlist('files'):
                file = File(post=obj,file=f )
                file.save()
            
            return HttpResponseRedirect( 
                reverse('Blog:detail', args=(obj.id,) ) )
            
            
def searchP(request):
    q = request.GET.get('q','')
    type = request.GET.get('type','0')
    #type :'0' 제목 검색
    if type=='0':
        #모델클래스.objects.fiter(): 특정조건을 만족하는 모든객체 추출
        #filter,get,exclude에 조건을 넣을때 (모델크랠스의 변수_명령어=값)
        #형태로 넣음
        #contains : 우변값이 해당 변수에 포함되있는 객체를 모두 추출
        list = Post.objects.fiter(headline__contains=q)
        return render(request, "Blog/templates/searchP.html",
                    {'list' : list} )
    elif type=='1': #type :'1' 글쓴이 검색
         user = User.objects.get(username = q )
         list = Post.objects.filter(author = user)
         return rendr (request, "Blog/templates/searchP.html",
                       {'list': list})
   
            
            
            
            
            
            
            
            
            
    














    
    
    
    
    
    
    

Django6/src/Blog/templates/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>블로그 어플리케이션</title>
</head>
<body>
	<a href="{% url 'vote:index' %}">투표 어플리케이션</a>
	<a href="{% url 'Blog:intex' %}">블로그 어플리케이션</a>
	{% if user.is_authenticated %}
		<p>{{user.username}}님 
		<a href="{%url 'customlogin:logout'%}"> 로그아웃</a> </p>
	{% else %}
		<a href="{%url 'customlogin:signup'%}">회원가입</a>
		<a href="{%url 'customlogin:signin'%}">로그인</a>	
	{% endif%}
	<hr> <!-- block : 해당 HTML파일을 확장하는 다른 HTML파일에서
	추가적으로 확장할 수 있는 영역을 지정 -->
	<!-- 검색창 -->
	<form action="{% url 'Blog:searhP' %}" method="GET">
	{% csrf_token %}
	<select name='type'>
		<opion value="0" selected>제목</opion>
		<opion value="1">글쓴이</opion>
	</select>
	<input type="text" name='q' />
	<input type="submit" value="검색" />
	</form>
	{% block content %}
	{% endblock %}
	<hr>
	<p>경기도 안산시 상록구 </p>
	<p>tel : 010-1234-5678 </p>
</body>
</html>









Django6/src/Blog/templates/detail.html
{% extends 'Blog/templates/base.html' %}
{% block content %}
<table>
	<tr>
		<th style="width:100px"> 제목</th>
		<th>{{ post.headline }}/{{ post.pub_date}}</th>
	</tr> 
	<tr>
		<th> 글쓴이 </th>
		<th>{{post.author.username}}</th>
	</tr>
	<tr>
		<th> 내용 </th>
		<td>
		<!-- 해당 Post객체에 연결된 file 객체를 전부 불러옴 -->
		{% for f in post.file_set.all %}
			<a href="{{f.file.url}}" download>다운로드</a><br>
		{% endfor %}
		{% for i in post.image_set.all %}
			<img width = 20% src="{{i.image.url}}"/>
		{% endfor %}
		<p>{{ post.content }}</p>
		 </td>
	</tr>
</table>
{% endblock %}



Django6/src/Blog/templates/index.html
<!-- extends : 기존 HTML 들을 확장하는 것을 명시 
해당 HTML파일의 block 부분만 수정가능 -->
{% extends 'Blog/templates/base.html' %}
{% block content %}
	<!-- page_obj : 이전,다음페이지에 대한 정보를 가진 객체 -->
	{% if page_obj.has_previous %}<!-- 이전페이지가 존재하는가? -->
		<a href="?page={{ page_obj.previous_page_number }}">이전페이지</a>	
	{% endif %}
	{% if page_obj.has_next %} <!-- 다음페이지가 존재하는가? -->
		<a href="?page={{ page_obj.next_page_number }}">다음페이지</a>
	{% endif %}
	<br>
	<table style="width:100%">
		<tr>
			<th>글번호</th>
			<th>제목</th>
			<th>작성자</th>
			<th>날짜</th>
		</tr>
		<!-- 뷰에서 'list'라는 이름에 객체들을 담아서 보냄 -->
		{% for post in list %}
			<tr>
				<td>
					{{post.id}}
				</td>
				<td>
					<a href="{% url 'Blog:detail' post.id %}">{{post.headline}}<a/>
				</td>
				<td>
					{{post.author.username}}
				</td>
				<td>
					{{post.pub_date}}
				</td>
			</tr>
		{% endfor %}
	</table>
	<a href="{% url 'Blog:posting' %}">글쓰기</a>
{% endblock %}













Django6/src/Blog/templates/posting.html
{% extends 'Blog/templates/base.html' %}
{% block content %}
<!-- 이미지, 파일을 폼에서 서버로 전달할때 폼에 아래와 같이 설정 
enctype="multipart/form-data" 설정 -->
<form method="POST" action="" enctype="multipart/form-data">
	{% csrf_token %}
	<table>
		{{ form.as_table }}
		<tr>
			<td>이미지 파일 : </td>
			<td><input type="file" accept="image/gif, image/jpeg" 
			multiple name="images"> </td>
		</tr>
		<tr>
			<td>첨부 파일 : </td>
			<td>
				<input type="file" multiple name='files'>
			</td>
		</tr>
	</table>
	<input type="submit" value="글쓰기"/>
</form>
{% endblock %}

Django6/src/Blog/templates/searchP.html
{% extends 'Blog/templates/base.html' %}
{% bloch content %}

{% if list %}
	<table style="width:100%">
			<tr>
				<th>글번호</th>
				<th>제목</th>
				<th>작성자</th>
				<th>날짜</th>
			</tr>
			<!-- 뷰에서 'list'라는 이름에 객체들을 담아서 보냄 -->
			{% for post in list %}
				<tr>
					<td>
						{{post.id}}
					</td>
					<td>
						<a href="{% url 'Blog:detail' post.id %}">{{post.headline}}<a/>
					</td>
					<td>
						{{post.author.username}}
					</td>
					<td>
						{{post.pub_date}}
					</td>
				</tr>
			{% endfor %}
{% else %}
	<p>검색 결과가 없습니다</p>
{% end if %}


{% endblock %} 