Django6/src/Blog/urls.py
'''
Created on 2018. 6. 30.

@author: KGITBank
'''
from django.urls import path
from .views import *
app_name='Blog'
urlpatterns=[
    #클래스뷰.as_view() : 클래스 뷰가 URL매칭시 사용
    path('', index.as_view(), name='index'),
    path('<int:post_id>/', detail, name='detail'),
    path('posting/', posting, name='posting')
    path('serach/', searchP, name='serachP')
    ]







Django6/src/Django6/urls.py
from django.contrib import admin
from django.urls import path, include
#해당 파일이 view 함수를 알아야되므로 from ~ import로 함수 추가
#urls.py와 views.py가 다른 파일 위치이므로 절대경로로 표현
from vote.views import * #vote폴더 안에 views파일 중 index함수 추가
urlpatterns = [
    path('admin/', admin.site.urls),
    #path(문자열, 함수명) : 웹 클라이언트가 문자열에 해당하는 URL로
    #접근 시 매칭된 함수를 호출함  
    #http://127.0.0.1:8000 주소로 접근시
    #vote 어플리케이션 내의 index 함수 호출
    #http://127.0.0.1:8000/vote/ 로 시작하는 URL들을
    #vote폴더 안에있는 urls 파이썬파일로 처리하도록 매칭
    path('vote/', include('vote.urls')),
    #include하면서 그룹이름을 정하고싶은 경우
    #path('vote/',include('vote.urls', namespace='vote') )
    path('login/', include('customlogin.urls') ),
    path('auth/', include('social_django.urls', namespace='social')  ),
    path('blog/',include('Blog.urls'))
]
from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)












Django6/src/customlogin/urls.py
'''
Created on 2018. 6. 24.

@author: KGITBank
'''
from django.urls.conf import path
from .views import *
#인증(로그인,로그아웃, 회원가입)에 관한 뷰가 있는 파일
from django.contrib.auth import views 
app_name = 'customlogin'
urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', signin, name='signin'),
    path('logout/',views.logout, name='logout')
    ]










Django6/src/vote/urls.py
'''
Created on 2018. 6. 17.

@author: KGITBank
'''
from django.urls import path
from .views import *
#{% url 'vote:index'%} reverse('vote:index')
app_name = 'vote'
urlpatterns =[
    path('', index, name='index'),
    path('<int:question_id>/', detail, name='detail'),
    path('vote/<int:question_id>/', vote, name='vote'),
    path('result/<int:question_id>/', result,name='result'),
    path('registerQ/', registerQ, name='registerQ' ),
    path('deleteQ/<int:question_id>/', deleteQ, name='deleteQ'),
    path('registerC/<int:question_id>/', registerC, name='registerC') ,
    path('deleteC/<int:choice_id>/', deleteC, name='deleteC'),
    path('updateQ/<int:question_id>/', updateQ, name='updateQ'),
]









Django6/src/vote/models.py
from django.db import models
#장고가 생성한 User모델클래스
from django.contrib.auth.models import User 
#모델 : 데이터를 어떤 형식으로 저장할지 표현하는 것
#모델 클래스 정의 후 객체를 만들어 사용
#class 클래스명(models.Model):
#MakeMigration, Migrate 시 Settings.py -> INSTALLED_APPS 변수에
#애플리케이션 이름이 들어가 있어야 사용할 수 있음

#모델 정의를 다한 후 해야되는 행동
#모델클래스가 변경된 애플리케이션에서 MakeMigration
#프로젝트 오른쪽클릭 -> dJango -> make migration 선택 
#-> 애플리케이션이름 입력

#변경사항을 데이터베이스에 적용 -> Migrate
#프로젝트 오른쪽클릭 -> dJango -> migrate 선택
class Question(models.Model):
    #User 모델클래스를 외래키로 참조
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    #models.CharField : 글자수 제한이 있는 문자열 저장시 사용
    question_text = models.CharField('질문 제목',max_length=200)
    #models.DateTimeField : 날짜 시간을 저장시 사용
    pub_date = models.DateTimeField('생성일자')
    #str : 각 객체를 문자열로 표현할 때 호출
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    choice_text = models.CharField('답변 제목',max_length=100)
    #IntegerField : 정수값을 저장할 수 있는 클래스
    votes = models.IntegerField('투표 수',default=0)
    #ForeignKey : 외래키. 다른테이블을 참조.
    #Question 객체 1개 : Choice 객체 n개
    #on_delete : 연결한 객체가 삭제됬을 때, 자신도 삭제될지 옵션을 지정
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    def __str__(self):
        return self.choice_text
    
    
    
    
    
    
    
    
    
    
    
    
    

Django6/src/vote/forms.py
#form : HTML코드에서 사용할 입력양식을 모델클래스에
#맞게 자동으로 만들어주는 기능 or 커스텀 입력양식을 만드는 기능을 제공함
#class 폼클래스명(ModelForm) : 모델클래스에 관한 폼을 정의
#class 폼클래스명(Form) : HTML에서 사용할 커스텀 폼을 정의 
from django.forms.models import ModelForm
from . import models

class QuestionForm(ModelForm):
    class Meta: #Meta클래스 정의를 통해 모델 클래스에 관한 정보 입력
        #model : 모델클래스 명(해당 폼이 매칭할 모델클래스 작성)
        #fields or exclude 중 1개 사용
        #fields : 해당 모델폼을 통해 클라이언트가 입력할 수 있는 데이터
        #         종류를 작성
        #exclude : 모델클래스의 속성중 명시한 속성을 제외한 속성들을 사용자 작성
        model = models.Question
        fields = ['question_text'] #question_text 속성만 사용자가 작성
        #exclude = ['pub_date'] #pub_date 속성을 제외한 모든 속성들을 
        #                        사용자가 작성
        
#모델 폼을 만들때, 모델 클래스를 참고하면서 제작 
#Choice 모델 클래스에 대한 모델폼 정의
#'choice_text'(답변제목), 'question'(질문)속성만 사용자가 입력하도록 허용
class ChoiceForm(ModelForm):
    class Meta:
        model = models.Choice
        fields = ['choice_text']
        #exclude = ['votes','question']











        
        
        
        

Django6/src/vote/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
#reverse(문자열, args=튜플)
#문자열에 해당하는 url 별칭을 찾고, 매개변수가 필요한 URL일 경우
#args 매개변수에 있는 튜플값으로 자동 매핑

from .models import Question, Choice
from django.http.response import HttpResponseRedirect

import datetime #파이썬 내장모듈, 시간정보를 얻을 때 사용

from .forms import * #QuestionForm

from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User

#from . import forms #forms.QuestionForm

#views.py : 내부적으로 동작할 행동들을 정의
#HTML 파일 전달, 검색, 등록, 삭제, 수정
#함수 or 클래스 형태로 뷰 구현
#함수형태로 구현시 반드시 첫번째 매개변수로 request 사용
#request : 웹 클라이언트의 요청에 대한 정보를 담고 있는 변수 
def index(request):
    print("index 함수 호출")
    #Question.objects.all()
    # : Question 모델 클래스에 저장된 모든 객체 추출
    list = Question.objects.all()
    #render(request, html 파일경로, 템플릿에 전달할 데이터-사전형
    return render(request, "vote/templates/index.html",
                  {'question_list' : list } )

def detail(request, question_id): 
    #get_object_or_404 : 모델클래스에 id값으로 객체 1개를 반환 함수
    #만약 객체를 못찾는 경우 클라이언트에게 404에러 메시지를 전달
    p = get_object_or_404(Question, pk = question_id )
    return render(request,"vote/templates/detail.html",
                  {'question' : p } )

def vote(request,question_id):
    #request.method : 클라이언트의 요청 방식이 저장된 변수
    #"GET" , "POST" 문자열 비교. 대소문자 구분 O
    if request.method == "POST":
        #request.POST : POST방식으로 들어온 데이터들
        #request.POST.get(문자열) : POST방식으로 들어온 데이터 중
        #name 속성의 값이 문자열과 같은 데이터를 추출
        #get 함수가 반환하는 데이터는 무조건 문자열
        id = request.POST.get('choice')
        obj = get_object_or_404(Choice,pk=id)
        obj.votes += 1
        obj.save() #모델클래스의 객체.save() : 변동사항을 저장
        #튜플을 만들때 요소 개수가 한개면 사칙연산에 사용하는 우선순위 괄호로
        #판단함. 때문에 튜플 요소 개수가 한개일 경우 끝에 쉼표를 입력
        return HttpResponseRedirect( 
            reverse('vote:result', args=( question_id, ) )   )
        #redirect(문자열) : 문자열에 해당하는 Url 주소로 변경
        #return redirect('/result/%s/' % (question_id) ) 

def result(request,question_id):
    #모델클래스.objects.get(조건) : 조건에 맞는 객체를 1개 찾아 반환
    data = Question.objects.get(id=question_id)
    return render(request, "vote/templates/result.html",
                  {'obj':data} )
#뷰 함수 정의 시 위에 @함수명을 작성하면, 해당 뷰를 호출하기 전에
#함수명에 해당하는 함수가 먼저 호출됨
@login_required
def registerQ(request):
    if request.method == "GET":
        form = QuestionForm() #QuestionForm 객체 생성, 사용하는 속성들이 공란으로 되어있음
        return render(request,"vote/templates/registerQ.html", 
                      {'form' : form} )
    elif request.method == "POST":
        form = QuestionForm(request.POST)
        #폼객채.is_valid() : 해당 폼에 입력값들이 에러가 없는지 확인
        #True, False 값 반환. 폼 객체 사용시 반드시 사용해야되는 함수
        if form.is_valid(): 
            #폼객체.save() : 해당 폼에 입력값들로 모델클래스 객체를
            #데이터베이스에 저장후 반환
            #폼객체.save(commit=False) : 데이터베이스에 바로 저장하지 않고
            #모델폼에서 모델클래스 객체로 변환 후 반환
            obj = form.save(commit=False)
            #name = request.POST.get('question_text')
            #obj = Question()
            #obj.question_text = name
            #request.user.get_username() : 로그인된 회원의 
            #                              username을 반환하는 함수
            user = User.objects.get(username=request.user.get_username() )
            obj.pub_date = datetime.datetime.now()
            obj.author=user
            obj.save()
            return HttpResponseRedirect(
                reverse('vote:detail', args=(obj.id, ) ) )
        else: #입력 양식에 문제가 있을 경우의 처리
            #템플릿으로 form 전달하면 사용자가 이전에 작성한 내용이 들어있는
            #상태로 전달함
            return render(request, "vote/templates/registerQ.html",
                          {'form' : form, 'error' : "입력이 잘못됬습니다."})
@login_required
def deleteQ(request, question_id):
    #pk = id
    obj = get_object_or_404(Question, pk = question_id)
    if obj.author.username != request.user.get_username():
        return render(request,"vote/templates/error.html",
                      {'error':"잘못된 접근 입니다.",
                       'returnURL' : reverse('vote:detail', 
                                             args=(question_id,) ) } )
    
    
    obj.delete() #해당 객체를 데이터베이스에서 삭제
    return HttpResponseRedirect( reverse('vote:index') )
@login_required
def deleteC(request, choice_id):
    #1. 뷰 구현 - deleteQ 함수 참고
    #Choice 객체 찾기
    obj = get_object_or_404(Choice, pk = choice_id)
    if request.user.get_username() != obj.question.author.username:
        return render(request,"vote/templates/error.html", {'error':"잘못된 접근 입니다.",'returnURL' : reverse('vote:detail', args=(obj.question.id,) ) } )
    
    
    id = obj.question.id #choice 객체 삭제전에 Question 객체의 id값을 저장
    obj.delete()
    #detail or index 페이지로 이동
    return HttpResponseRedirect( reverse("vote:detail", args=(id,) ) ) 
    #return HttpResponseRedirect( reverse("votd:index") ) 
    #2. urls 등록 - vote/urls.py에서 수정
    #3. detail.html 파일(vote/templates/detail.html) 수정
    #각 답변 항목별로 '삭제'링크 만들기
    
#registerQ 함수 참고    
def registerC(request, question_id):
    obj = get_object_or_404(Question, pk = question_id)
    # obj.author  해당 Quetion 객체를 작성한 User 객체
    #해당 질문을 쓴 글쓴이 이름과 로그인된 유저의 이름을 비교
    if request.user.get_username() != obj.author.username:
        return render(request,"vote/templates/error.html", {'error':"본인이 작성한 글이 아닙니다.",'returnURL' : reverse('vote:detail',args=(question_id,) ) })
    
    if request.method == "GET":
        #폼 객체 생성
        form = ChoiceForm()
        #render함수로 HTML파일 로드 + 탬플릿에 폼객체 전달
        return render(request,"vote/templates/registerC.html",
                      {'form':form, 'name' : obj.question_text})
        #뷰 코드 작성 및 HTML파일 생성까지
    elif request.method == "POST":
        #폼객체 생성(클라이언트의 데이터를 넣음)
        form = ChoiceForm(request.POST)
        #폼의 에러 확인
        if form.is_valid():
            #모델클래스 객체를 데이터베이스에 저장 및 반환
            obj1 = form.save(commit=False)  
            obj1.question = obj
            obj1.save()
            #다른 페이지로 전달
            return HttpResponseRedirect(
                reverse('vote:detail', args=(obj1.question.id, ) ))
        else:
            #에러 전달
            return render(request,"vote/templates/registerC.html",
                          {'form': form, 'error':"입력에 오류가 있음"
                           ,'name' : obj.question_text })
        
@login_required
def updateQ(request, question_id):
    obj = get_object_or_404(Question, pk = question_id)
    # obj.author  해당 Quetion 객체를 작성한 User 객체
    #해당 질문을 쓴 글쓴이 이름과 로그인된 유저의 이름을 비교
    if request.user.get_username() != obj.author.username:
        return render(request,"vote/templates/error.html",
                      {'error':"본인이 작성한 글이 아닙니다.",
                       'returnURL' : reverse('vote:detail', 
                                             args=(question_id,) ) })
    if request.method == "GET":
        #Question 객체에 저장된 값을 QuestionForm 객체를 생성할 때 입력
        #모델폼의 생성자에 instance 매개변수는 이미 생성된 모델클래스의 객체를
        #담을 수 있음
        form = QuestionForm(instance = obj)
        return render(request,"vote/templates/updateQ.html",
                      {'form':form})
    elif request.method == "POST":
        #이미 생성된 Question 객체에 내용을 클라이언트가 작성한 내용으로
        #덮어씌움
        form = QuestionForm(request.POST,instance=obj )
        if form.is_valid():
            question = form.save(commit=False)
            question.pub_date = datetime.datetime.now()
            question.save()
            return HttpResponseRedirect(
                reverse('vote:detail', args=(question.id, ) ) )
        else:
            return render(request,"vote/templates/updateQ.html",
                          {'form':form, 'error':"유효하지 않은 데이터"})
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    


Django6/src/vote/templates/detail.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<!-- { % : 파이썬 문법 사용   { { : 해당 영역에 데이터를 입력-->
	<!-- Question 객체 안에있는 question_text값을 입력 -->
	<h1>{{ question.question_text  }}</h1>
	<h3>작성자 : {{ question.author.username }}</h3>
	<form action="{% url 'vote:vote' question.id %}" method="POST">
		{% csrf_token %} 
		<!-- 해당 폼이 유효한 폼인지, 다른 클라이언트에서 접근하지 못하도록
		자동발급하는 일회용 키 -->
		<!-- question.choice_set.all : Question 객체에 엮여있는 
		모든 Choice객체들을 리스트형태로 반환  -->
		{% for choice in question.choice_set.all  %}
			<input type="radio" name="choice" value="{{ choice.id }}" 
			id="choice{{forloop.counter}}" />
			<label for="choice{{forloop.counter}}">{{ choice.choice_text }} </label>
			{% if user.username == question.author.username %}
				<a href="{% url 'vote:deleteC' choice.id %}">삭제</a>
			{% endif %}
			<br>
		{% endfor %}
		<input type="submit" value="투표"/>
	</form>
	<a href="{% url 'vote:index' %}">메인페이지로 돌아가기</a>
	<!-- detail.html, result.html (공통사항)-->
	<!-- <a> 태그를 이용해 '메인페이지로 돌아가기' 링크 생성
	     클릭시 메인페이지(index.html)로 돌아가는 링크 만들기 -->
	<!-- result.html 만 적용 -->
	<!-- <a> 태그를 이용해 '다시투표하기' 링크 생성.
	     클릭시 해당 질문의 detail.html로 전환  -->
	<br><br>
	{% if user.username == question.author.username  %}
		<a href="{% url 'vote:deleteQ' question.id %}">글 삭제</a>
		<a href="{% url 'vote:updateQ' question.id %}">글 수정</a>
		<a href="{% url 'vote:registerC' question.id %}">답변 등록</a>
	{% endif %}
</body>
</html>





Django6/src/vote/templates/error.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>잘못된 접근입니다.</title>
</head>
<body>
	{% if error %}
		<h1> {{ error }} </h1>
	{% endif %}
	
	<a href="{{returnURL}}">해당 글로 넘어가기</a>
	
	
</body>
</html>

Django6/src/vote/templates/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<!-- 로그인 여부에 따른 링크 보여주기 -->
	<!-- 탬플릿에서 로그인 여부확인시 user 변수를 이용함 -->
	<!-- 로그인된 유저의 ID를 추출 : user.username -->
	<!-- 로그인 여부 확인 : user.is_authenticated 
	                       -> True, False 반환 -->
	{% if user.is_authenticated %}
		<p>{{ user.username }}님 환영합니다.</p>
		<a href="{% url 'customlogin:logout'%}">로그아웃</a>
	{% else %}
		<a href="{% url 'customlogin:signup' %}">회원가입</a>
		<a href="{% url 'customlogin:signin' %}">로그인</a>
		<br> <!-- 엔터 -->
	{% endif %}
	<hr> <!-- 가로로 줄긋기 -->
	
	<!-- HTML파일에서 파이썬 코드를 삽입할 수 있음
	for ~ in , if 문, 외 django에서 만든 함수 사용 가능  -->
	<!-- 단, 함수를 사용할 때 소괄호 생략 
	ex) 파이썬코드 -> Question.objects.all()  
	HTML내의 파이썬 코드 -> Question.objecs.all  -->
	<!-- index 뷰 함수에서 question_list에 넣은 값을 변수처럼 사용 -->
	{%  for question in question_list %}
		<!-- url '문자열' '해당url에 필요한 값' -->
		<a href="{% url 'vote:detail' question.id %}">{{ question.question_text }} </a>
		<br> <!-- <br> : 한줄 띄우기 -->
	{% endfor %}
	<!-- if 사용시 endif로 영역 지정
	for 사용시 endfor로 영역 지정 -->
	<br><br>
	<a href="{% url 'vote:registerQ'  %}">질문등록하기</a>
	<br>

</body>
</html>











Django6/src/vote/templates/registerC.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>{{name}}의 답변 등록</h1>
	{% if error %}
		<p><b>{{error}}</b></p>
	{% endif %}
	<form action="" method = "POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="등록">
	</form>
</body>
</html>








Django6/src/vote/templates/registerQ.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>

	<h1>질문 생성</h1>
	<!-- view에서 'error' 변수에 값을 넣었는지 확인 -->
	{% if error %}
		<p><strong>{{error}}</strong></p>
	{% endif %}
	<form action="" method="POST">
		{% csrf_token %}
		<table>
		<!-- 폼객체.as_p <input>, <label>를 <p>를 이용해서 HTML코드로 변환 -->
		<!-- 폼객체.as_table : <input>와 <label>를 테이블형태의 HTML코드로 변환 -->
			{{ form.as_table }} 
		</table>
		<!-- 
		<input type="text"  name="question_text" maxlength="200" id="a"/>
		<label for="a">질문 이름</label> -->
		<input type="submit" value="만들기"/>
	</form>
</body>
</html>

Django6/src/vote/templates/result.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>{{ obj.question_text }}</h1>
	<h3>{{ obj.pub_date}}</h3>
	<ul>
		{% for item in obj.choice_set.all %}
			<li>{{item.choice_text}}의 투표 수 : {{item.votes}} </li>
		{% endfor %}
	</ul>
	<!--  { % % } -->
	<a href="{% url 'vote:index' %}">메인페이지로 돌아가기</a>
	<a href="{% url 'vote:detail' obj.id %}">다시투표하기</a>
</body>
</html>








Django6/src/vote/templates/updateQ.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>질문 수정</h1>
	{% if error %}
		<p><b>{{error}}</b></p>
	{% endif %}
	<form action="" method =POST >
		{% csrf_token %}
		<table>
			{{form.as_table}}
		</table>
		<input type="submit" value="수정">
	</form>
</body>
</html>

